server:
  port: 9091

spring:
  application:
    name: Product Microservice
  data:
    mongodb:
      host: localhost
      port: 27017
      database: shopping
  profiles:
    active: dev1

logging:
  file:
    name: c:\logs\product.log
    #path: c:\logs  #spring.log
  logback:
    rollingpolicy:
      max-file-size: 50KB
 # level:
   # root: INFO

# actuator specific
management:
  endpoints:
    web:
      exposure:
        include:
          - '*'
  endpoint:
    health:
      show-details: ALWAYS

product:
  currencies:
    - INR
    - USD
    - EUR

---
server:
  port: 9094

spring:
  config:
    activate:
      on-profile:
        - prod
